### ISSUE TITLE
`<main>': undefined method `include_path' for Libyajl2:Module

### ISSUE THREAD

**Issue by markdavison** [palfrey/raspberry-chef#10]
Trying to get this working on my RPI2 B on buster lite. Any ideas what is wrong? 

Thanks in advance.

Using berkshelf 4.3.3
Installing ffi-yajl 2.4.0 with native extensions
STDERR: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/var/lib/gems/2.5.0/gems/ffi-yajl-2.4.0/ext/ffi_yajl/ext/encoder
/usr/bin/ruby2.5 -r ./siteconf20210628-15489-1ggpxn5.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.5
extconf.rb:9:in `<main>': undefined method `include_path' for Libyajl2:Module
(NoMethodError)
Did you mean?  include

extconf failed, exit code 1

**Comment by palfrey** [comment]
Not a clue TBH. Haven't seen that one before, but I haven't setup a new system in a long while. Looks like a version of https://github.com/chef/ffi-yajl/issues/91 which isn't desperately helpful.
